// Code generated by _tmpl/utils.h.tmpl. DO NOT EDIT.

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include <stdlib.h>
#include "adbc.h"

struct AdbcError* Db2ErrorFromArrayStream(struct ArrowArrayStream*, AdbcStatusCode*);
AdbcStatusCode Db2DatabaseGetOption(struct AdbcDatabase*, const char*, char*, size_t*,
                                      struct AdbcError*);
AdbcStatusCode Db2DatabaseGetOptionBytes(struct AdbcDatabase*, const char*, uint8_t*,
                                           size_t*, struct AdbcError*);
AdbcStatusCode Db2DatabaseGetOptionDouble(struct AdbcDatabase*, const char*, double*,
                                            struct AdbcError*);
AdbcStatusCode Db2DatabaseGetOptionInt(struct AdbcDatabase*, const char*, int64_t*,
                                         struct AdbcError*);
AdbcStatusCode Db2DatabaseInit(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode Db2DatabaseNew(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode Db2DatabaseRelease(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode Db2DatabaseSetOption(struct AdbcDatabase* db, const char* key,
                                      const char* value, struct AdbcError* err);
AdbcStatusCode Db2DatabaseSetOptionBytes(struct AdbcDatabase*, const char*,
                                           const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode Db2DatabaseSetOptionDouble(struct AdbcDatabase*, const char*, double,
                                            struct AdbcError*);
AdbcStatusCode Db2DatabaseSetOptionInt(struct AdbcDatabase*, const char*, int64_t,
                                         struct AdbcError*);

AdbcStatusCode Db2ConnectionCancel(struct AdbcConnection*, struct AdbcError*);
AdbcStatusCode Db2ConnectionCommit(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode Db2ConnectionGetInfo(struct AdbcConnection* cnxn, const uint32_t* codes,
                                      size_t len, struct ArrowArrayStream* out,
                                      struct AdbcError* err);
AdbcStatusCode Db2ConnectionGetObjects(struct AdbcConnection* cnxn, int depth,
                                         const char* catalog, const char* dbSchema,
                                         const char* tableName, const char** tableType,
                                         const char* columnName,
                                         struct ArrowArrayStream* out,
                                         struct AdbcError* err);
AdbcStatusCode Db2ConnectionGetOption(struct AdbcConnection*, const char*, char*,
                                        size_t*, struct AdbcError*);
AdbcStatusCode Db2ConnectionGetOptionBytes(struct AdbcConnection*, const char*,
                                             uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode Db2ConnectionGetOptionDouble(struct AdbcConnection*, const char*,
                                              double*, struct AdbcError*);
AdbcStatusCode Db2ConnectionGetOptionInt(struct AdbcConnection*, const char*, int64_t*,
                                           struct AdbcError*);
AdbcStatusCode Db2ConnectionGetStatistics(struct AdbcConnection*, const char*,
                                            const char*, const char*, char,
                                            struct ArrowArrayStream*, struct AdbcError*);
AdbcStatusCode Db2ConnectionGetStatisticNames(struct AdbcConnection*,
                                                struct ArrowArrayStream*,
                                                struct AdbcError*);
AdbcStatusCode Db2ConnectionGetTableSchema(struct AdbcConnection* cnxn,
                                             const char* catalog, const char* dbSchema,
                                             const char* tableName,
                                             struct ArrowSchema* schema,
                                             struct AdbcError* err);
AdbcStatusCode Db2ConnectionGetTableTypes(struct AdbcConnection* cnxn,
                                            struct ArrowArrayStream* out,
                                            struct AdbcError* err);
AdbcStatusCode Db2ConnectionInit(struct AdbcConnection* cnxn, struct AdbcDatabase* db,
                                   struct AdbcError* err);
AdbcStatusCode Db2ConnectionNew(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode Db2ConnectionReadPartition(struct AdbcConnection* cnxn,
                                            const uint8_t* serialized,
                                            size_t serializedLen,
                                            struct ArrowArrayStream* out,
                                            struct AdbcError* err);
AdbcStatusCode Db2ConnectionRelease(struct AdbcConnection* cnxn, struct AdbcError* err);
AdbcStatusCode Db2ConnectionRollback(struct AdbcConnection* cnxn,
                                       struct AdbcError* err);
AdbcStatusCode Db2ConnectionSetOption(struct AdbcConnection* cnxn, const char* key,
                                        const char* val, struct AdbcError* err);
AdbcStatusCode Db2ConnectionSetOptionBytes(struct AdbcConnection*, const char*,
                                             const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode Db2ConnectionSetOptionDouble(struct AdbcConnection*, const char*, double,
                                              struct AdbcError*);
AdbcStatusCode Db2ConnectionSetOptionInt(struct AdbcConnection*, const char*, int64_t,
                                           struct AdbcError*);

AdbcStatusCode Db2StatementBind(struct AdbcStatement* stmt, struct ArrowArray* values,
                                  struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode Db2StatementBindStream(struct AdbcStatement* stmt,
                                        struct ArrowArrayStream* stream,
                                        struct AdbcError* err);
AdbcStatusCode Db2StatementCancel(struct AdbcStatement*, struct AdbcError*);
AdbcStatusCode Db2StatementExecuteQuery(struct AdbcStatement* stmt,
                                          struct ArrowArrayStream* out, int64_t* affected,
                                          struct AdbcError* err);
AdbcStatusCode Db2StatementExecutePartitions(struct AdbcStatement* stmt,
                                               struct ArrowSchema* schema,
                                               struct AdbcPartitions* partitions,
                                               int64_t* affected, struct AdbcError* err);
AdbcStatusCode Db2StatementExecutePartitionsTrampoline(
    struct AdbcStatement* stmt, struct ArrowSchema* schema,
    struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode Db2StatementExecuteSchema(struct AdbcStatement*, struct ArrowSchema*,
                                           struct AdbcError*);
AdbcStatusCode Db2StatementGetOption(struct AdbcStatement*, const char*, char*, size_t*,
                                       struct AdbcError*);
AdbcStatusCode Db2StatementGetOptionBytes(struct AdbcStatement*, const char*, uint8_t*,
                                            size_t*, struct AdbcError*);
AdbcStatusCode Db2StatementGetOptionDouble(struct AdbcStatement*, const char*, double*,
                                             struct AdbcError*);
AdbcStatusCode Db2StatementGetOptionInt(struct AdbcStatement*, const char*, int64_t*,
                                          struct AdbcError*);
AdbcStatusCode Db2StatementGetParameterSchema(struct AdbcStatement* stmt,
                                                struct ArrowSchema* schema,
                                                struct AdbcError* err);
AdbcStatusCode Db2StatementNew(struct AdbcConnection* cnxn, struct AdbcStatement* stmt,
                                 struct AdbcError* err);
AdbcStatusCode Db2StatementPrepare(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode Db2StatementRelease(struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode Db2StatementSetOption(struct AdbcStatement* stmt, const char* key,
                                       const char* value, struct AdbcError* err);
AdbcStatusCode Db2StatementSetOptionBytes(struct AdbcStatement*, const char*,
                                            const uint8_t*, size_t, struct AdbcError*);
AdbcStatusCode Db2StatementSetOptionDouble(struct AdbcStatement*, const char*, double,
                                             struct AdbcError*);
AdbcStatusCode Db2StatementSetOptionInt(struct AdbcStatement*, const char*, int64_t,
                                          struct AdbcError*);
AdbcStatusCode Db2StatementSetSqlQuery(struct AdbcStatement* stmt, const char* query,
                                         struct AdbcError* err);
AdbcStatusCode Db2StatementSetSubstraitPlan(struct AdbcStatement* stmt,
                                              const uint8_t* plan, size_t length,
                                              struct AdbcError* err);

AdbcStatusCode AdbcDriverDb2Init(int version, void* rawDriver, struct AdbcError* err);

static inline void Db2errRelease(struct AdbcError* error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void Db2_release_error(struct AdbcError* error);

struct Db2Error {
  char* message;
  char** keys;
  uint8_t** values;
  size_t* lengths;
  int count;
};

void Db2ReleaseErrWithDetails(struct AdbcError* error);

int Db2ErrorGetDetailCount(const struct AdbcError* error);
struct AdbcErrorDetail Db2ErrorGetDetail(const struct AdbcError* error, int index);

int Db2ArrayStreamGetSchemaTrampoline(struct ArrowArrayStream* stream,
                                        struct ArrowSchema* out);
int Db2ArrayStreamGetNextTrampoline(struct ArrowArrayStream* stream,
                                      struct ArrowArray* out);
